name: Bitcoin Price Prediction Counter

on:
  workflow_dispatch: # 添加此行以允許手動觸發
  schedule:
    - cron: cron: '0 8 * * 0' # 每週日 08:00 觸發
  repository_dispatch:
    types: [price_prediction]

jobs:
  update_predictions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: main #main分支
      - name: Verify prediction files
        run: |
          ls -la predictions/
          cat predictions/rise.txt || echo "rise.txt not found"
          cat predictions/fall.txt || echo "fall.txt not found"
      - name: Get existing prediction counts
        id: read_predictions
        run: |
          mkdir -p predictions
          echo "::set-output name=rise::$(cat predictions/rise.txt 2>/dev/null || echo 0)"
          echo "::set-output name=fall::$(cat predictions/fall.txt 2>/dev/null || echo 0)"
          
      - name: Initialize prediction files
        run: |
          mkdir -p predictions
          [ -f predictions/rise.txt ] || echo 0 > predictions/rise.txt
          [ -f predictions/fall.txt ] || echo 0 > predictions/fall.txt
          
      - name: Process prediction
        if: github.event.action == 'price_prediction'
        run: |
          PREDICTION=$(echo "${{ github.event.client_payload.prediction }}" | tr -d '\n')
          if [ "$PREDICTION" == "rise" ]; then
            echo $(( ${{ steps.read_predictions.outputs.rise }} + 1 )) > predictions/rise.txt
          elif [ "$PREDICTION" == "fall" ]; then
            echo $(( ${{ steps.read_predictions.outputs.fall }} + 1 )) > predictions/fall.txt
          fi

      - name: Update README
        run: |
          # 讀取當前 README 內容
          current_readme=$(cat README.md)

          # 構建新的預測內容，包括時間戳
          prediction_content="## Bitcoin Price Predictions\nGreen (Rise): $(cat predictions/rise.txt || echo 0)\nRed (Fall): $(cat predictions/fall.txt || echo 0)\nUpdated at: $(date)"
          
          # 使用 sed 替換占位符
          updated_readme=$(echo "$current_readme" | sed -e "/<!-- BUTTON_VOTE_PLACEHOLDER -->/c\\$prediction_content")
          
          # 將更新的內容寫回 README.md
          echo "$updated_readme" > README.md

          # 配置 Git 信息
          git config user.name "GitHub Action Bot"
          git config user.email "actions@github.com"
          
          # 添加 README.md 和更新的預測文件到 Git
          git add README.md predictions/
          
          # 如果有更改則提交和推送，否則跳過提交
          if ! git diff --cached --quiet; then
            git commit -m "Update prediction counts"
            git push
          else
            echo "No changes to commit or push."
          fi
